### ISSUE TITLE
プロダクトリンクが切れているかもしれない？？

### ISSUE THREAD

**Issue by kinjo1130** [K-kind/Punct#104]
### Summary
https://app.quden.io/videos?videoId=6384011dd5badf00233305e7

こんな感じでリンクにアクセスできない？？
### TODO

**Comment by K-kind** [comment]
@AFURO-1130 

ご指摘いただきありがとうございます！
こちらのアプリは、学習用に作成・公開させていただいていたものですが、インフラ費用削減のためすでにサービスは停止させていただいておりました。

せっかくアクセスいただき申し訳ありませんが、READMEと説明欄からリンクを削除させていただきます🙇‍♂️

**Comment by kinjo1130** [comment]
それならよかったです！
